name: 'three_pillars_lakehouse'
version: '1.0.0'
config-version: 2

profile: 'local-dev'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  three_pillars_lakehouse:
    +materialized: table

seeds:
  three_pillars_lakehouse:
    +column_types:
      id: varchar(50)

vars:
  pillars:
    - code
    - observability 
    - guard